name: Deployment DEV
on: 
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name:  Deployment DEV
        run:  |
          echo "Deploying to dev" 
        